### ISSUE TITLE
but a lot of devices doesn't encrypt Sensitive Information before sending it does this mean that all these devices should have a CVE opened for them?

### ISSUE THREAD

**Issue by minanagehsalalma** [filipi86/ConnectBoxDOCSIS-3.0#2]
"in this case we can to think about vulnerability known by MITRE as Cleartext Transmission of Sensitive Information (http://cwe.mitre.org/data/definitions/319.html)"

this shouldn't even be a problem as you know if it's http or not properly configured https then the attacker can simply edit the page before it reaches the target with the removed encryption !

**Comment by filipi86** [comment]
Hi @minanagehsalalma,
Good observation (...this shouldn't even be a problem...), but the point is this vulnerability is known by MITRE and it has an identification, basically we can agree that this vulnerability is the flaw by design. ( using http mode, right?), so if we think in corporate environment we can have a big problem.

Best Regards,
Filipi

**Comment by minanagehsalalma** [comment]
@filipi86 so i can open CVEs of routers that have the same flaw ?

**Comment by filipi86** [comment]
@minanagehsalalma If you find, I believe yes 👍 , But of course, You should report it to manufacturer, However the majority company don't look at that and prefer take the risk 👎

**Comment by minanagehsalalma** [comment]
> You should report it to manufacturer

@filipi86 Hmm... about that what if the manufacturer patched it in newer models only ? And left the older models without any patch.



> However the majority company don't look at that and prefer take the risk

Yup i think they won't care about it at all... in local level there is nothing you can really do about it.

Would it be a problem if i opened the CVEs without reporting?

**Comment by minanagehsalalma** [comment]
@filipi86 hi mate what do you think?

**Comment by filipi86** [comment]
@minanagehsalalma usually manufacturer patched the newer models, and YES, they won't care about, because sometimes they think that is just "Local level Vulnerability", but if this router is sold for SmallBusiness Companies, if the "Person" responsible for the management don't know nothing about security..
The recommendation is Open CVE with reporting the vulnerability to manufacturer, you can report without reporting but mayba can be risk for you.

**Comment by minanagehsalalma** [comment]
> you can report without reporting but mayba can be risk for you.

@filipi86  I will try my luck ;)





> they think that is just "Local level Vulnerability

Hmm. What do you suggest that would be a fix for the problem?  
There is no valid https in offline level without installing the cert that would come with the router tho.
